import "@/app/_styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children, a, b }) {
  return (
    <html lang="en">
      <body>
        {children}
        {a} {b}
      </body>
    </html>
  );
}
